name: Electron Package

on:
  push:
    branches: [main]

jobs:
  package-electron:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
      - run: npx electron-builder --win
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: my-electron-app
          path: dist/
